name: in_app_purchase_ohos_example
description: Demonstrates how to use the in_app_purchase_ohos plugin.
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase_ohos:
    # When depending on this package from a real application you should use:
    #   in_app_purchase_ohos: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  in_app_purchase_platform_interface: ^1.0.0
  shared_preferences:
    git:
      url: https://gitee.com/openharmony-sig/flutter_packages.git
      path: packages/shared_preferences/shared_preferences

dev_dependencies:
  # build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
