name: local_auth_ohos
description: Ohos implementation of the local_auth plugin.
repository: https://gitee.com/openharmony-sig/flutter_packages/tree/master/packages/local_auth/local_auth_ohos
issue_tracker: https://gitee.com/openharmony-sig/flutter_packages/issues
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: local_auth
    platforms:
      ohos:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
        dartPluginClass: LocalAuthOhos

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <0.19.0"
  local_auth_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
