name: webview_flutter_ohos
description: A Flutter plugin that provides a WebView widget on Ohos.
repository: https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 3.9.3

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      ohos:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin
        dartPluginClass: OhosWebViewPlatform

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_platform_interface: ^2.4.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  pigeon: ^9.2.4
